language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "nightly"
before_script:
    - (cd test/commonmark && ./spec.sh)
script:
    - make test
    - python3 -m test.commonmark
after_success:
    - pip install coveralls
    - coverage run -a -m unittest
    - coverage run -a -m test.commonmark
    - coveralls
